vince: powerstats: remove unused variable
error:
device/xiaomi/vince/powerstats/service.cpp:56:10: error: unused variable 'isDebuggable' [-Werror,-Wunused-variable]
    bool isDebuggable = android::base::GetBoolProperty("ro.debuggable", false);
         ^
1 error generated.

Signed-off-by: KenHV <kenhv@null.net>